backend:
  name: git-gateway
  branch: master

media_folder: site/assets/img

collections:
  - label: Posts
    name: posts
    description: List of posts
    folder: site/blog
    extension: md
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Content
        name: body
        widget: markdown